odom_frame: odom
base_link_frame: base_link
world_frame: map
map_frame: map
publish_tf: true

# gmapping output configuration
odom0: /odom
odom0_config: [true, true, true,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_queue_size: 10
odom0_nodelay: true

# IMU configuration
imu0: /imu/data
imu0_config: [false, false, false,
              true,  true,  true,
              false, false, false,
              true,  true,  true,
              true,  true,  true]
imu0_differential: false
imu0_queue_size: 4

imu0_orientation_covariance: 0.15
